
services:
  python:
    image: python:3.9
    container_name: python_service
    volumes:
      - .:/app
    working_dir: /app
    command: python3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    volumes:
      - .:/root/.ollama
    ports:
      - "1337:11434"

  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu_service
    command: tail -f /dev/null

  mysql:
    image: mysql:5.7
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: wikirag123
      MYSQL_DATABASE: wikirag
      MYSQL_USER: wikirag
      MYSQL_PASSWORD: wikirag123
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --init-file=/data/application/init.sql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql


volumes:
  mysql_data: {}
