services:
  python:
    image: python:3.9
    container_name: python_service
    volumes:
      - .:/app
    working_dir: /app
    command: python3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "8080:8080"

  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu_service
    command: tail -f /dev/null